/**
 * Marketplace Safety & Compliance Sanitizer
 * 
 * Guarantees 100% stock agency compliance (Adobe Stock, Shutterstock, Freepik, Getty Images / iStock, Alamy, Vecteezy).
 * Eliminates trademarks, subjective hype words, keyword stuffing, and spam that cause
 * reviewer rejections or contributor account penalties.
 */

// Trademark brand names strictly prohibited in commercial stock metadata
export const PROHIBITED_TRADEMARKS = new Set([
  'apple', 'iphone', 'ipad', 'ipod', 'macbook', 'imac', 'ios', 'airpods', 'apple watch', 'siri',
  'google', 'android', 'pixel', 'youtube', 'chromebook', 'gmail',
  'microsoft', 'windows', 'xbox', 'office 365', 'excel', 'word', 'powerpoint',
  'sony', 'playstation', 'ps4', 'ps5', 'bravia', 'walkman',
  'samsung', 'galaxy', 'bixby',
  'nike', 'adidas', 'puma', 'reebok', 'under armour', 'new balance', 'asics',
  'gucci', 'prada', 'chanel', 'louis vuitton', 'hermes', 'rolex', 'dior', 'versace', 'armani', 'zara', 'h&m',
  'ferrari', 'lamborghini', 'porsche', 'bmw', 'mercedes', 'mercedes-benz', 'audi', 'tesla', 'toyota', 'honda', 'ford', 'chevrolet', 'volkswagen', 'nissan', 'hyundai', 'jeep', 'harley-davidson',
  'amazon', 'alexa', 'kindle', 'prime',
  'facebook', 'meta', 'instagram', 'whatsapp', 'tiktok', 'twitter', 'snapchat', 'linkedin', 'pinterest', 'threads',
  'adobe', 'photoshop', 'illustrator', 'lightroom', 'premiere', 'indesign', 'after effects',
  'openai', 'chatgpt', 'dall-e', 'dalle', 'midjourney', 'stable diffusion', 'flux',
  'coca cola', 'coca-cola', 'coke', 'pepsi', 'red bull', 'starbucks', 'mcdonalds', "mcdonald's", 'burger king', 'kfc', 'subway', 'nestle',
  'disney', 'marvel', 'star wars', 'pixar', 'pokemon', 'pokémon', 'nintendo', 'lego', 'barbie', 'mattel', 'hasbro',
  'netflix', 'spotify', 'hulu', 'uber', 'airbnb', 'canon', 'nikon', 'leica', 'fujifilm', 'panasonic', 'hasselblad'
]);

// Subjective buzzwords, junk terms & spam phrases that trigger instant automated bot rejections
export const PROHIBITED_BUZZWORDS = new Set([
  'universal', 'marketplace', 'marketplaces',
  'best', 'masterpiece', 'award winning', 'award-winning', 'trending', 'viral', 'top rated',
  'photorealistic', 'hyperrealistic', 'ultra realistic', 'hyper-realistic', 'ultra-detailed',
  '8k', '8k resolution', '4k resolution', '16k', 'ultra hd', 'hd wallpaper', 'desktop wallpaper',
  'ai', 'ai generated', 'ai art', 'generated by ai', 'artificial intelligence', 'midjourney style', 'prompt',
  'free', 'free download', 'download', 'cheap', 'royalty free download',
  'stock photo', 'stock image', 'stock picture', 'stock footage', 'commercial stock', 'commercial stock photo',
  'stock asset', 'stock photography', 'concept', 'commercial', 'vulval',
  'photo of', 'picture of', 'image of', 'an image of', 'a photograph of', 'shot of',
  'good', 'nice', 'great', 'awesome', 'amazing', 'cool', 'pretty', 'fine', 'perfect',
  'looking', 'viewing', 'something', 'thing', 'things', 'stuff', 'item', 'items',
  'file', 'files', 'upload', 'downloadable', 'low quality', 'high quality', 'hq', 'hd'
]);

// Common English stop words and useless filler that should never be solitary stock keywords
export const STOCK_STOP_WORDS = new Set([
  'universal', 'marketplace', 'marketplaces', 'concept', 'commercial', 'asset', 'vulval',
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'with', 'by', 'of', 'from',
  'up', 'about', 'into', 'through', 'after', 'over', 'between', 'out', 'against', 'during', 'without',
  'before', 'under', 'around', 'among', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have',
  'has', 'had', 'do', 'does', 'did', 'this', 'that', 'these', 'those', 'it', 'its', 'as', 'such',
  'very', 'can', 'will', 'just', 'should', 'now', 'suitable', 'really', 'much', 'more', 'most',
  'etc', 'e.g', 'ie', 'also', 'any', 'all', 'both', 'each', 'few', 'other', 'some', 'than', 'too'
]);

export interface ComplianceReport {
  isSafe: boolean;
  score: number; // 0 to 100
  titleCompliant: boolean;
  keywordsCompliant: boolean;
  removedTrademarks: string[];
  removedBuzzwords: string[];
  removedDuplicates: number;
  warnings: string[];
  suggestions: string[];
  sanitizedTitle: string;
  sanitizedKeywords: string;
}

/**
 * Sanitizes a title for stock agency submission:
 * - Removes prohibited trademarks and AI/spam buzzwords
 * - Strips redundant prefixes like "Photo of", "Image showing"
 * - Cleans illegal punctuation characters
 * - Ensures ideal word count (7-15 words) and length (30-140 chars)
 * - Guarantees proper capitalization
 */
export function sanitizeStockTitle(rawTitle: string, marketplace: string = 'universal'): { title: string; removedWords: string[] } {
  let title = (rawTitle || '').trim();
  const removedWords: string[] = [];

  // Remove surrounding quotes
  title = title.replace(/^["'`\s]+|["'`\s]+$/g, '');

  // Strip redundant conversational prefixes
  title = title.replace(/^(photo of|picture of|image of|photograph of|shot of|close up of|scenic view of|an image of|a photo of|stock photo of|illustration of|vector of)\s+/i, '');

  // Clean illegal characters that trigger reviewer flags: #, @, $, %, *, ~, ^, {, }, [, ], (, ), |, \, /, _
  title = title.replace(/[/\\#@$%*~^{}[\]()|<>_]/g, ' ');

  // Collapse multiple spaces/dashes
  title = title.replace(/[-_]{2,}/g, ' ').replace(/\s{2,}/g, ' ').trim();

  // Word-by-word trademark and spam check
  const words = title.split(/\s+/);
  const cleanWords: string[] = [];

  for (let i = 0; i < words.length; i++) {
    const rawWord = words[i];
    const cleanWord = rawWord.toLowerCase().replace(/[^a-z0-9]/g, '');

    // Check two-word phrases first (e.g. "coca cola", "apple watch")
    if (i < words.length - 1) {
      const nextWord = words[i + 1].toLowerCase().replace(/[^a-z0-9]/g, '');
      const twoWord = `${cleanWord} ${nextWord}`;
      if (PROHIBITED_TRADEMARKS.has(twoWord) || PROHIBITED_BUZZWORDS.has(twoWord)) {
        removedWords.push(twoWord);
        i++; // skip next word
        continue;
      }
    }

    if (PROHIBITED_TRADEMARKS.has(cleanWord)) {
      removedWords.push(rawWord);
      continue;
    }

    if (PROHIBITED_BUZZWORDS.has(cleanWord)) {
      removedWords.push(rawWord);
      continue;
    }

    cleanWords.push(rawWord);
  }

  let finalTitle = cleanWords.join(' ').trim();

  // Strip trailing punctuation like periods or commas (stock titles do not end with periods)
  finalTitle = finalTitle.replace(/[.,;:!?\s]+$/, '');

  // If title became too short or empty, provide a clean descriptive fallback
  if (finalTitle.split(/\s+/).length < 4 || finalTitle.length < 15) {
    finalTitle = rawTitle.replace(/[/\\#@$%*~^{}[\]|<>]/g, ' ').trim();
  }

  // Capitalize first character
  if (finalTitle.length > 0) {
    finalTitle = finalTitle.charAt(0).toUpperCase() + finalTitle.slice(1);
  }

  return { title: finalTitle, removedWords };
}

/**
 * Sanitizes and optimizes keywords for stock agencies:
 * - Strips all trademarks and prohibited buzzwords
 * - Deduplicates case-insensitively while preserving natural priority
 * - Ensures top 10 keywords are the most critical visual nouns
 * - Removes stop words and single-character junk
 * - Formats cleanly as comma-separated tags
 */
export function sanitizeStockKeywords(
  rawKeywords: string | string[],
  titleContext: string = '',
  targetCount: number = 50,
  singleWordOnly: boolean = false
): { keywords: string; removedTrademarks: string[]; removedBuzzwords: string[]; duplicateCount: number } {
  const inputList = Array.isArray(rawKeywords)
    ? rawKeywords
    : (rawKeywords || '').split(',').map(k => k.trim());

  const removedTrademarks: string[] = [];
  const removedBuzzwords: string[] = [];
  let duplicateCount = 0;

  const seen = new Set<string>();
  const validKeywords: string[] = [];

  for (const rawTag of inputList) {
    let tag = rawTag.toLowerCase().trim();

    // Remove unwanted symbols including brackets and parentheses
    tag = tag.replace(/[/\\#@$%*~^{}[\]()<>"'`;!?_]/g, '').trim();

    if (!tag || tag.length < 2) continue;

    // Single word formatting if requested
    if (singleWordOnly && tag.includes(' ')) {
      tag = tag.split(/\s+/)[0];
    }

    // Trademark check
    if (PROHIBITED_TRADEMARKS.has(tag)) {
      removedTrademarks.push(tag);
      continue;
    }

    // Buzzword check
    if (PROHIBITED_BUZZWORDS.has(tag)) {
      removedBuzzwords.push(tag);
      continue;
    }

    // Stop word check
    if (STOCK_STOP_WORDS.has(tag)) {
      continue;
    }

    // Pure number check (allow meaningful years 1900-2099 or route numbers)
    if (/^\d+$/.test(tag)) {
      const num = parseInt(tag, 10);
      if (!(num >= 1950 && num <= 2050)) {
        continue;
      }
    }

    // Deduplication check
    if (seen.has(tag)) {
      duplicateCount++;
      continue;
    }

    seen.add(tag);
    validKeywords.push(tag);
  }

  // Ensure top keywords reflect the core nouns from the sanitized title for highest SEO rank
  if (titleContext) {
    const titleWords = titleContext
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, '')
      .split(/\s+/)
      .filter(w => w.length > 2 && !STOCK_STOP_WORDS.has(w) && !PROHIBITED_TRADEMARKS.has(w) && !PROHIBITED_BUZZWORDS.has(w));

    // Move title nouns to the front of validKeywords if present, or prepend if missing
    for (let i = titleWords.length - 1; i >= 0; i--) {
      const tw = titleWords[i];
      const existingIdx = validKeywords.indexOf(tw);
      if (existingIdx !== -1) {
        validKeywords.splice(existingIdx, 1);
        validKeywords.unshift(tw);
      } else if (validKeywords.length < targetCount) {
        validKeywords.unshift(tw);
        seen.add(tw);
      }
    }
  }

  const finalKeywords = validKeywords.slice(0, targetCount).join(', ');

  return {
    keywords: finalKeywords,
    removedTrademarks,
    removedBuzzwords,
    duplicateCount
  };
}

/**
 * Validates and provides an end-to-end Agency Compliance Report
 */
export function validateMetadataCompliance(
  title: string,
  keywords: string,
  description?: string,
  marketplace: string = 'universal'
): ComplianceReport {
  const titleResult = sanitizeStockTitle(title, marketplace);
  const kwResult = sanitizeStockKeywords(keywords, titleResult.title, 50);

  const warnings: string[] = [];
  const suggestions: string[] = [];

  const wordCount = titleResult.title.split(/\s+/).length;
  if (wordCount < 6) {
    warnings.push(`Title is relatively short (${wordCount} words). Stock buyers prefer 7-15 descriptive words.`);
  } else if (wordCount > 20) {
    warnings.push(`Title is quite long (${wordCount} words). Consider trimming to under 18 words to prevent truncation.`);
  }

  const kwList = kwResult.keywords.split(',').map(k => k.trim()).filter(Boolean);
  if (kwList.length < 25) {
    warnings.push(`Keyword count is ${kwList.length}. Generating 35-50 keywords maximizes sales reach on Adobe Stock and Shutterstock.`);
  }

  if (titleResult.removedWords.length > 0) {
    suggestions.push(`Automatically stripped ${titleResult.removedWords.length} prohibited/trademark terms from title to protect your account.`);
  }

  if (kwResult.removedTrademarks.length > 0) {
    suggestions.push(`Removed ${kwResult.removedTrademarks.length} trademark brand names from keywords.`);
  }

  if (kwResult.removedBuzzwords.length > 0) {
    suggestions.push(`Removed ${kwResult.removedBuzzwords.length} subjective buzzwords (e.g. "photorealistic", "best", "ai").`);
  }

  let score = 100;
  if (titleResult.removedWords.length > 0) score -= 10;
  if (kwResult.removedTrademarks.length > 0) score -= 15;
  if (kwResult.removedBuzzwords.length > 0) score -= 10;
  if (kwList.length < 20) score -= 15;
  if (wordCount < 5) score -= 10;
  score = Math.max(score, 50);

  return {
    isSafe: kwResult.removedTrademarks.length === 0 && titleResult.removedWords.length === 0,
    score,
    titleCompliant: wordCount >= 6 && wordCount <= 22,
    keywordsCompliant: kwList.length >= 25,
    removedTrademarks: kwResult.removedTrademarks,
    removedBuzzwords: [...titleResult.removedWords, ...kwResult.removedBuzzwords],
    removedDuplicates: kwResult.duplicateCount,
    warnings,
    suggestions,
    sanitizedTitle: titleResult.title,
    sanitizedKeywords: kwResult.keywords
  };
}
